<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222104514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE main (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, block_text TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE project DROP block_content');
        $this->addSql('ALTER TABLE project DROP image');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE main');
        $this->addSql('ALTER TABLE project ADD block_content TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD image VARCHAR(255) DEFAULT NULL');
    }
}
