<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260308094209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE model (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, short_id VARCHAR(10) NOT NULL, status VARCHAR(32) NOT NULL, version_number INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D79572D9F8496E51 ON model (short_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_model_project_version ON model (project_id, version_number)');
        $this->addSql('CREATE INDEX IDX_D79572D9F675F31B ON model (author_id)');
        $this->addSql('CREATE INDEX IDX_D79572D9166D1F9C ON model (project_id)');
        $this->addSql('CREATE TABLE model_tab_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tab_key VARCHAR(64) NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_model_tab_data_model_tab ON model_tab_data (model_id, tab_key)');
        $this->addSql('CREATE INDEX IDX_D9EB8C857975B7E7 ON model_tab_data (model_id)');
        $this->addSql('ALTER TABLE model ADD CONSTRAINT FK_D79572D9F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE model ADD CONSTRAINT FK_D79572D9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE model_tab_data ADD CONSTRAINT FK_D9EB8C857975B7E7 FOREIGN KEY (model_id) REFERENCES model (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE model DROP CONSTRAINT FK_D79572D9F675F31B');
        $this->addSql('ALTER TABLE model DROP CONSTRAINT FK_D79572D9166D1F9C');
        $this->addSql('ALTER TABLE model_tab_data DROP CONSTRAINT FK_D9EB8C857975B7E7');
        $this->addSql('DROP TABLE model');
        $this->addSql('DROP TABLE model_tab_data');
    }
}
