<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408181943 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE model_time_params (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, investment_start_date DATE NOT NULL, investment_duration_months INT NOT NULL, commercial_operation_duration_months INT NOT NULL, forecast_step VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B83A78E97975B7E7 ON model_time_params (model_id)');
        $this->addSql('ALTER TABLE model_time_params ADD CONSTRAINT FK_B83A78E97975B7E7 FOREIGN KEY (model_id) REFERENCES model (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE model_time_params DROP CONSTRAINT FK_B83A78E97975B7E7');
        $this->addSql('DROP TABLE model_time_params');
    }
}
